### PR TITLE
import: pexec module

### PR DESCRIPTION
**Pull request by dwsJason**
launch pgx and pgZ files, plus view LBM and 256 picture types

### CODE REVIEW

**Comment by paulscottrobson** [comment]
Hi. 
As discussed I'm quite happy to add this, but ideally I need a git pull or somewhere I can download it from (so as to get the latest), and also bulk.csv is generated automatically, though integrating your launcher is no problem.

**Comment by dwsJason** [comment]
Hi, when we discussed it, I shared this link with you on discord.  But perhaps it got missed in all the traffic?   https://github.com/dwsJason/f256/tree/develop/merlin32/pexec
you build it, but running the build.bat file


> Hi. As discussed I'm quite happy to add this, but ideally I need a git pull or somewhere I can download it from (so as to get the latest), and also bulk.csv is generated automatically, though integrating your launcher is no problem.

Hi, when we discussed it, I shared this link with you on discord.  But perhaps it got missed in all the traffic?   https://github.com/dwsJason/f256/tree/develop/merlin32/pexec
you build it, but running the build.bat file

**Comment by dwsJason** [comment]
I think maybe I misunderstood what you need.

**Comment by dwsJason** [comment]
I guess you could rejects the PR, and just pull the file from here?  https://github.com/dwsJason/superbasic/blob/pexec/howto/update/pexec.bin

**Comment by paulscottrobson** [comment]
Ah, yes. My bad. We did. I can't run batch files though. The best thing is to just pull that file and add it to the build. I presume it doesn't need anything else other than to be put in the Flash ROMs. 

I'll add it today sometime (probably !) but it won't be official until 35.

**Comment by paulscottrobson** [comment]
It is integrated into the upload and starts (thought it gives a file open $0A error when starting ?)
Rather than use the pull request, would it be better to have a build directory in https://github.com/dwsJason/f256 and then I can directly download it from there as part of the release build, so new releases will automatically pick up the latest version of your app.

**Pull request closed without merging**
