### PR TITLE
Argument passing and logo fix

### PR DESCRIPTION
**Pull request by csoren**
This PR adds support for a new, standardized method of passing arguments between programs started on an F256 computer. The handling of the "slash" command now performs tokenization and building of the argument array for the launched program.

The bootscreen logo for F256 Jr has been updated, and the new version is included.

### CODE REVIEW

**Comment by paulscottrobson** [comment]
Hi, as I'm not really working full time on this do you want to either fork it or for me to transfer the various repositories. I'm still happy to advise and contribute.

Paul

**Comment by csoren** [comment]
I have forked it to the repository https://github.com/FoenixRetro/f256-superbasic in the FoenixRetro organization. This organization is going to serve as a hub for further development and distribution of the firmware. The firmware as a whole is being moved out of the SuperBASIC repository, and into its own umbrella project. If you want to transfer the repositories to the FoenixRetro organization, that would be very generous of you. As opposed to forking, the benefit would be automatic redirection as I understand it.

**Comment by paulscottrobson** [comment]
I've tried this and it comes up with "You don’t have the permission to create public repositories on FoenixRetro" ; I'm not sure if it will give you the option to accept it or not ?

**Comment by csoren** [comment]
No, unfortunately it doesn't. You have been invited to the organization, so you should be able to create repositories now.

**Pull request merged**
